const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //admin
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILED: 'FETCH_GENDER_FAILED',

    FETCH_ROLE_START: 'FETCH_ROLE_START',
    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILED: 'FETCH_ROLE_FAILED',

    FETCH_POSITION_START: 'FETCH_POSITION_START',
    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAILED: 'FETCH_POSITION_FAILED',

    ADD_NEW_USER_REDUX_START: 'ADD_NEW_USER_REDUX_START',
    ADD_NEW_USER_REDUX_SUCCESS: 'ADD_NEW_USER_REDUX_SUCCESS',
    ADD_NEW_USER_REDUX_FAILED: 'ADD_NEW_USER_REDUX_FAILED',

    FETCH_USERS_START: 'FETCH_USERS_START',
    FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
    FETCH_USERS_FAILED: 'FETCH_USERS_FAILED',

    DELETE_USERS_START: 'DELETE_USERS_START',
    DELETE_USERS_SUCCESS: 'DELETE_USERS_SUCCESS',
    DELETE_USERS_FAILED: 'DELETE_USERS_FAILED',

    UPDATE_USERS_START: 'UPDATE_USERS_START',
    UPDATE_USERS_SUCCESS: 'UPDATE_USERS_SUCCESS',
    UPDATE_USERS_FAILED: 'UPDATE_USERS_FAILED',

    FETCH_DOCTOR_HOME_START: 'FETCH_DOCTOR_HOME_START',//fetchDoctorHome
    FETCH_DOCTOR_HOME_SUCCESS: 'FETCH_DOCTOR_HOME_SUCCESS',
    FETCH_DOCTOR_HOME_FAILED: 'FETCH_DOCTOR_HOME_FAILED',

    GET_DOCTOR_NAME_START: 'GET_DOCTOR_NAME_START',
    GET_DOCTOR_NAME_SUCCESS: 'GET_DOCTOR_NAME_SUCCESS',
    GET_DOCTOR_NAME_FAILED: 'GET_DOCTOR_NAME_FAILED',

    CREATE_OR_UPDATE_DOCTOR_INFO_START: 'CREATE_OR_UPDATE_DOCTOR_INFO_START',
    CREATE_OR_UPDATE_DOCTOR_INFO_SUCCESS: 'CREATE_OR_UPDATE_DOCTOR_INFO_SUCCESS',
    CREATE_OR_UPDATE_DOCTOR_INFO_FAILED: 'CREATE_OR_UPDATE_DOCTOR_INFO_FAILED',

    FETCH_DOCTOR_DETAIL_INFO_BY_ID_START: 'FETCH_DOCTOR_DETAIL_INFO_BY_ID_START',
    FETCH_DOCTOR_DETAIL_INFO_BY_ID_SUCCESS: 'FETCH_DOCTOR_DETAIL_INFO_BY_ID_SUCCESS',
    FETCH_DOCTOR_DETAIL_INFO_BY_ID_FAILED: 'FETCH_DOCTOR_DETAIL_INFO_BY_ID_FAILED',

    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',

    FETCH_TIME_START: 'FETCH_ TIME_START',
    FETCH_TIME_SUCCESS: 'FETCHTIME_SUCCESS',
    FETCH_TIME_FAILED: 'FETCH_TIME_FAILED',

    CREATE_BULK_SCHEDULE_START: 'CREATE_BULK_SCHEDULE_START',
    CREATE_BULK_SCHEDULE_SUCCESS: 'CREATE_BULK_SCHEDULE_SUCCESS',
    CREATE_BULK_SCHEDULE_FAILED: 'CREATE_BULK_SCHEDULE_FAILED'

})

export default actionTypes;